version: "3.9"

services:
  backend:
    container_name: nodejs
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 8008:8000
    volumes:  
      - ./src:/server
    links:
      - database
  database:
    image: mongo:6.0.1
    restart: unless-stopped
    hostname: database
    container_name: database
    ports:
      - 27019:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: bengali
    volumes:
      - mongo_data:/data/db     
volumes:
  mongo_data:
